version: "3.9"

services:
  learn-with-vy-mongodb:
    image: mongo:7
    container_name: learn-with-vy-mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: learn_with_vy_db
    volumes:
      - mongo_data:/data/db

  learn_with_vy-postgres:
    image: postgres:16-alpine
    container_name: learn-with-vy-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: learn_with_vy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mongo_data:
  postgres_data: